spring:
  application:
    name: vacancyManager
    version: 1.0.0

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
